return {
  en = {
    name_game = "Medals and Orders",
    score = "Score",
    play = "Play",
    home = "Home",
    back = "Back",
    pause = "Pause",
    restart = "Restart",
    setting = "Settings",
    victory = "Victory",
    time_out = "Time out",
    stars_out = "Stars out",
    removestat = "Reset statistic",
    played = "Played",
    answer = "times\nAnswered correctly",
    Times = "Times",
    languages = "Language",
    Russua = "Russia",
    English = "English",
    thema = "Theme",
    sounds = "Sounds",
    Music = "Music",
    font = "Font",
    fontsizee = "Font size",
    correct = "Correct",
    age_msg = "выше %{age}.",
    phone_msg = {
      one = "you have one new message.",
      other = "you have %{count} new messages."
    }
  },
  ru = {
    name_game = "Медали и Ордена",
    score = "Очки",
    play = "Играть",
    home = "Домой",
    back = "Назад",
    pause = "Пауза",
    restart = "Заново",
    setting = "Настройки",
    victory = "Победа",
    time_out = "Время вышло",
    stars_out = "Закончились звезды",
    removestat = "Сбросить статистику",
    played = "Сыграно",
    answer = "раз\nОтвечено правильно",
    Times = "Раз",
    languages = "Язык",
    Russua = "Russia",
    English = "English",
    thema = "Темы",
    sounds = "Звуки",
    Music = "Музыка",
    font = "Шрифт",
    fontsizee = "Размер шрифта",
    correct = "Правильно",
    age_msg = "выше %{age}.",
    phone_msg = {
      one = "you have one new message.",
      other = "you have %{count} new messages."
    }
  }
}
